/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Guijva;

/**
 *
 * @author uriigrao
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu(String nameUser) {
        initComponents();
        veriryAdmin(nameUser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAltaParti = new javax.swing.JButton();
        buttonModiParti = new javax.swing.JButton();
        buttonBorrarParti = new javax.swing.JButton();
        buttonVerParti = new javax.swing.JButton();
        buttonAllParti = new javax.swing.JButton();
        buttonDarAltaUser = new javax.swing.JButton();
        buttonBorrarUser = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonAltaParti.setText("Dar de Alta Partitura");
        buttonAltaParti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAltaPartiActionPerformed(evt);
            }
        });

        buttonModiParti.setText("Modificar Partitura");
        buttonModiParti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModiPartiActionPerformed(evt);
            }
        });

        buttonBorrarParti.setText("Borrar Partitura");

        buttonVerParti.setText("Ver Partituras");

        buttonAllParti.setText("Totales");

        buttonDarAltaUser.setText("Dar Alta Usuario");

        buttonBorrarUser.setText("Borrar Usuario");

        buttonExit.setText("Log Out");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonAllParti, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonVerParti, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonBorrarParti, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonModiParti, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAltaParti)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(buttonExit)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonBorrarUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDarAltaUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(buttonAltaParti)
                .addGap(35, 35, 35)
                .addComponent(buttonModiParti)
                .addGap(35, 35, 35)
                .addComponent(buttonBorrarParti)
                .addGap(35, 35, 35)
                .addComponent(buttonVerParti)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAllParti)
                    .addComponent(buttonDarAltaUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBorrarUser)
                    .addComponent(buttonExit))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAltaPartiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAltaPartiActionPerformed
        Alta pestaa = new Alta(null, true);
        pestaa.setVisible(true);
        pestaa.setLocationRelativeTo(null);
        Menu.this.dispose();
    }//GEN-LAST:event_buttonAltaPartiActionPerformed

    private void buttonModiPartiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModiPartiActionPerformed
        Modificar pestaa = new Modificar(null, true);
        pestaa.setVisible(true);
        pestaa.setLocationRelativeTo(null);
        Menu.this.dispose();
    }//GEN-LAST:event_buttonModiPartiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAllParti;
    private javax.swing.JButton buttonAltaParti;
    private javax.swing.JButton buttonBorrarParti;
    private javax.swing.JButton buttonBorrarUser;
    private javax.swing.JButton buttonDarAltaUser;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonModiParti;
    private javax.swing.JButton buttonVerParti;
    // End of variables declaration//GEN-END:variables

    private void veriryAdmin(String nameUser) {
        if (!nameUser.equals("admin")) {
            buttonDarAltaUser.setVisible(false);
            buttonBorrarUser.setVisible(false);
        }
    }

}
